services:
  - type: web
    name: twig-ticketr
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DOCUMENT_ROOT
        value: /var/www/html/public
      - key: APP_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /var/www/html/storage/users.json
    
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 1
    
  healthCheckPath: /
  autoDeploy: true
