[package]
name = "twig-ticketr"
version = "0.1.0"
description = "Ticket Management System with Twig"

[dependencies]
php = "^8.2"

[fs]
public = "./public"
storage = "./storage"

[command]
name = "start"
value = "php -S 0.0.0.0:8080 -t public"

[[command.environ]]
name = "DOCUMENT_ROOT"
value = "./public"

[scripts]
setup = "composer install --no-dev --optimize-autoloader"

[webserver]
port = 8080
static-dir = "public"